IBM/Train-Custom-Speech-Model

- src/public/css/main.css
- src/util.ts
- views/head.pug
- views/home.pug
- views/pages/corpus-status.pug
- views/pages/custom-lm.pug
- views/pages/lm-status.pug
- views/pages/stt.pug
- views/user/login.pug
Changed it so the pages use the Bootstrap CSS library.
> Update styling of pages

- src/public/js/check-lm.js
- src/util.ts
use Buffer to wrap the corpus instead of using stream
> fix addCorpus

- src/controllers/pages.ts
- src/public/css/main.css
- src/public/js/words.js
- views/pages/list-words.pug
This is the initial UI for custom words.
> Add initial word list UI

- services.sample.json
This sample file shows what is needed for the backend to work.
> Add sample services JSON file

- cmd/README.md
- cmd/add_audio.py
- cmd/add_corpus.py
- cmd/create_acoustic_model.py
- cmd/create_language_model.py
- cmd/delete_acoustic_model.py
- cmd/delete_audio.py
- cmd/delete_corpus.py
- cmd/delete_language_model.py
- cmd/env.py
- cmd/list_acoustic_model.py
- cmd/list_all_models.py
- cmd/list_audio.py
- cmd/list_corpus.py
- cmd/list_language_model.py
- cmd/reset_language_model.py
- cmd/train_acoustic_model.py
- cmd/train_language_model.py
- cmd/transcribe.py
Check the README.md for details
> Add command line style python code

- data/convert_rtf.py
- data/fixup.sed
> Add code to convert and clean text data

- .travis.yml
Want to see if the travis-ci Github App integration works.
> Testing travis integration

- README.md
Updating the steps to install web service, download data, prepare data
> A round of update

- README.md
> Add complete instructions for command line

- server/controllers/api.ts
- server/controllers/user.ts
- server/util.ts
Declare two credential types:
- STTCredentialUserPass
- STTCredentialAPIKey
And STTCredential is either one of them
> Add union like type for credential object

- client/src/App.js
- client/src/Routes.js
- client/src/config.js
- client/src/pages/Audio.css
- client/src/pages/Audio.js
- client/src/pages/Login.js
- client/src/pages/Train.js
- client/src/pages/Transcribe.js
- client/src/pages/Words.js
- model/user.json
- server/controllers/api.ts
- server/routes/api.ts
- server/util.ts
Can now add audio resource after transcribing if transcription is incorrect.
Can now view/delete audio resources.
Can now train acoustic model (this uses the custom language model)
> Add Acoustic model UI support

- model/user.json
- package.json
- server/controllers/api.ts
- server/routes/api.ts
- server/server.ts
- server/util.ts
- services.sample.json
Create a class to wrap all functions we have so far. And
attach the object to Express.Request and is available for
middleware now.
> Refactor util.js

- README.md
Update instructions to set up credential, add bash loop to process rtf files, and a few other tweaks.
> Resolve Issue #20 and #21

- cmd/env.py
The python scripts can use either the old USERNAME/PASSWORD credential or the new IAM API key.
Add help message to show how to use API key by setting them in the USERNAME/PASSWORD environment variables.
Resolve issue #23
> Update help message on USERNAME and PASSWORD 

- .travis.yml
- README.md
- client/src/pages/Transcribe.js
- add linting of client directory to travis
- fixed lint issue in source
- added lint badge to readme
> add travis test

- client/src/App.js
- client/src/pages/Audio.css
- client/src/pages/Audio.js
- client/src/pages/Corpora.css
- client/src/pages/Corpora.js
- client/src/pages/Login.js
- client/src/pages/Transcribe.js
- client/src/pages/Words.js
- server/controllers/api.ts
Also, just return 500 status code when Watson STT API fails.
> Add ability to upload corpus and audio resources in UI

- client/src/App.js
- client/src/pages/Audio.js
- client/src/pages/Corpora.js
- client/src/pages/Login.js
- client/src/pages/Train.js
- client/src/pages/Transcribe.js
- client/src/pages/Words.js
This patch ensures that if a response is not an OK response,
an error box is shown to the user to clue them in on what went wrong.
> Ensure error messages appear in UI

- README.md
- cmd/transcribe.py
This makes it similar to the GUI.  Update the README to describe how to make correction to the transcription and retrain for better accuracy.
> Adapt the command line transcribe.py to allow any mix of base/custom models

- .vscode/settings.json
- package.json
- server/controllers/api.ts
- server/controllers/user.ts
- server/routes/api.ts
- server/server.ts
- server/types/cfenv.d.ts
- server/util.ts
- tslint.json
Use tslint to enforce coding conventions
> Enable tslint

- client/README.md
- client/src/components/AppliedRoute.js
Add some basic information to the client readme.
> Update client README

- server/controllers/api.ts
model -> languageModel
Signed-off-by: Paul Van Eck <pvaneck@us.ibm.com>
> Fix wrong key issue

- client/src/pages/Corpora.js
- package.json
- server/server.ts
increase the bodyparser json limit to 2MB and
properly handle the error in react client.
fix: #44 
> Increase the bodyparser limit to 2MB

- client/README.md
- client/package.json
- client/src/App.js
- client/src/config.js
- client/src/pages/Audio.js
- client/src/pages/Corpora.js
- client/src/pages/Login.js
- client/src/pages/Train.js
- client/src/pages/Transcribe.js
- client/src/pages/Words.js
- package.json
- server/server.ts
There were issues with long lasting file upload requests going through the dev fetch proxy.
* Enable CORS for the UI origin
* Increase server request timeout
* Use defined endpoint in all fetch requests in UI
Signed-off-by: Paul Van Eck <pvaneck@us.ibm.com>
> Create API_ENDPOINT config for UI

- ACKNOWLEDGEMENTS.md
- README.md
- added credits to acknowledgment file
- updated readme to use txt file extension for corpus file
> doc updates

- client/src/App.js
- client/src/pages/Audio.js
- client/src/pages/Corpora.js
- client/src/pages/Login.js
- client/src/pages/Train.js
- client/src/pages/Transcribe.js
- client/src/pages/Words.js
- client/src/pages/util.js
- server/controllers/api.ts
- server/util.ts
Always check response.ok after calling `fetch()` and
use the `catch()` section to handle error case.
> Generalize the error handling of `fetch()`

- README.md
That code section should be bash not python
> change python to bash

- server/controllers/api.ts
> Add new line for the transcribe result

- data/fixup.sed
> Separate paragraph to sentences

- client/src/config.js
- client/src/pages/Transcribe.css
- client/src/pages/Transcribe.js
- package.json
- server/controllers/api.ts
- server/server.ts
- server/util.ts
After client post the audio file to server side,
server calls recognize API via WebSocket and get
interim results and send the results back to client
via WebSocket.
> Call recognize via WebSocket

- cmd/add_audio.py
- cmd/add_corpus.py
- cmd/env.py
- cmd/list_acoustic_model.py
- cmd/list_audio.py
- cmd/list_corpus.py
- cmd/list_language_model.py
- cmd/requirements.txt
- cmd/train_acoustic_model.py
- cmd/train_language_model.py
> nit: print to print()
